### PR TITLE
Fix tests for Plone 52

### PR DESCRIPTION
**Pull request by tschorr**
This PR

* fixes tests for Plone 5.2
* installs clamd for integration testing
* introduces Github Actions and discontinues Travis CI
* removes the unused robot test boilerplate

### CODE REVIEW

**Comment by tschorr** [comment]
If you consider merging this, please squash the commits. It's mostly me fighting with Github Actions.

**Review by sneridagh — APPROVED** [review]
LGTM!!

**Comment by sneridagh** [comment]
@tschorr do you have the rights for the release?

**Comment by tschorr** [comment]
Thanks!. PyPI release? No, I'm not a maintainer, but I'd appreciate a PyPI release of the package.

**Comment by tisto** [comment]
@tschorr I can make a release. We need to merge https://github.com/collective/collective.clamav/pull/9 first though because I am unable to create a local build with the current version to being able to make a release.

**Pull request merged**
